Repository treydock/puppet-module-globus, pull requests merged in 2022-08, with the labels that each got.

#33 Fix ensure_packages usage
  manifests/repo/el.pp
  metadata.json
Labels: bugfix

#34 Require python module >= 6.3.0
  data/os/Debian.yaml
  manifests/python.pp
  metadata.json
Labels: backwards-incompatible

#32 Set allowed puppet-epel version to < 5.0.0
  metadata.json
Labels: enhancement
